### ISSUE TITLE
Different PDF adapters support

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento-hackathon/Imagine2017#38]
**Description**
Default PDF implementation in Magento is too hard to customize for extension developers, even changing default font requires substantial effort. It is proposed to add support for the `html2pdf` tool.

**Acceptance Criteria**
* PDF rendering middleware is implemented in Magento, to allow integration with different tools.
* Adapter for `html2pdf` is implemented.
* Implemented Solution is used in invoice, shipment and credit memo PDFs

**Comment by JosephLeedy** [comment]
I think this is a duplicate of #3.
